### ISSUE TITLE
SQLFluff failing due to ImportError

### ISSUE THREAD

**Issue by jasluong** [yu-iskw/action-sqlfluff#61]
sqlfluff has been failing for us since yesterday around 3pm GMT, with the following error:

ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (/usr/local/lib/python3.9/site-packages/dbt/exceptions.py). 

We haven't changed any configs or anything - think the issue started around the same time that dbt went down too.

Rest of the error is below:

`  Traceback (most recent call last):
    File "/usr/local/bin/sqlfluff", line 5, in <module>
      from sqlfluff.cli.commands import cli
    File "/usr/local/lib/python3.9/site-packages/sqlfluff/__init__.py", line 6, in <module>
      from sqlfluff.api import lint, fix, parse, list_rules, list_dialects
    File "/usr/local/lib/python3.9/site-packages/sqlfluff/api/__init__.py", line 4, in <module>
      from sqlfluff.api.simple import lint, fix, parse, APIParsingError
    File "/usr/local/lib/python3.9/site-packages/sqlfluff/api/simple.py", line 4, in <module>
      from sqlfluff.core import (
    File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/__init__.py", line 9, in <module>
      from sqlfluff.core.linter import Linter
    File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/__init__.py", line 6, in <module>
      from sqlfluff.core.linter.linter import Linter
    File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 23, in <module>
      from sqlfluff.core.rules import get_ruleset
    File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/rules/__init__.py", line 12, in <module>
      for plugin_rules in get_plugin_manager().hook.get_rules():
    File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
      pm.load_setuptools_entrypoints(project_name)
    File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
      plugin = ep.load()
    File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
      module = import_module(match.group('module'))
    File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/__init__.py", line 3, in <module>
      from sqlfluff_templater_dbt.templater import DbtTemplater
    File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 17, in <module>
      from dbt.exceptions import (
  ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (/usr/local/lib/python3.9/site-packages/dbt/exceptions.py)`
  
  Screenshot below:
  
  
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/101130140/214849844-c5391303-32b6-42ab-a39e-b9c018b7c833.png">

**Comment by yaozhang09** [comment]
related to https://github.com/sqlfluff/sqlfluff/issues/4315

**Comment by yu-iskw** [comment]
According to my research, we have to use dbt-core 1.3 or less until the change is released.

- https://github.com/sqlfluff/sqlfluff/pull/4317

**Comment by yu-iskw** [comment]
@jasluong @sohaibqureshii @yaozhang09 Can you make sure your actions with v3.6.0.

https://github.com/yu-iskw/action-sqlfluff/releases/tag/v3.6.0
