### ISSUE TITLE
SQLFluff linting job failing due to missing CompilationException from dbt.exceptions 

### ISSUE THREAD

**Issue by AnkitDhingra-at** [yu-iskw/action-sqlfluff#87]
The SQLFluff linting was working as expected with the following versions: SQLFluff version `1.4.5` with  DBT Version `1.2` in DBT Cloud. But recently it started failing with the following error:

```
Traceback (most recent call last):
    File "/usr/local/bin/sqlfluff", line 5, in <module>
      from sqlfluff.cli.commands import cli
    File "/usr/local/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 518, in <module>
      def lint(
    File "/usr/local/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 218, in core_options
      get_plugin_manager().hook.get_templaters()
    File "/usr/local/lib/python3.10/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
      pm.load_setuptools_entrypoints(project_name)
    File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
      plugin = ep.load()
    File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
      module = import_module(match.group('module'))
    File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "/usr/local/lib/python3.10/site-packages/sqlfluff_templater_dbt/__init__.py", line 3, in <module>
      from sqlfluff_templater_dbt.templater import DbtTemplater
    File "/usr/local/lib/python3.10/site-packages/sqlfluff_templater_dbt/templater.py", line 17, in <module>
      from dbt.exceptions import (
  ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (/usr/local/lib/python3.10/site-packages/dbt/exceptions.py)
```

**Comment by yu-iskw** [comment]
We recommend use sqlfluff 2.0.7 now, because sqlfluff 2.0 or later can handle the changes of exceptions of dbt-core.
